title: Enterstry
description: Systemische Klarheit f√ºr IT-nahe Organisationen

url: "https://www.enterstry.de"  

theme: minima #classic
markdown: kramdown

minima:
  skin: classic
  include_css:
    - /assets/css/custom.css

plugins:
  - jekyll-paginate
  - jekyll-sitemap

excerpt_separator: "<!--more-->"
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /:categories/:title/